[package]
name = "echo-rust"
version = "0.1.0"
authors = ["David Stainton <dstainton415@gmail.com>"]

[dependencies]
grpc            = "~0.5"
protobuf        = "~2"
futures         = "~0.1"
futures-cpupool = "~0.1"
tls-api            = "0.1.*"
tls-api-native-tls = "0.1.*"
